### ISSUE TITLE
Mobile roster screen formatted improperly

### ISSUE THREAD

**Issue by Excelasaurus** [EnrgyzerBunny/dotatrash#34]
**Describe the bug**
On mobile, roster screen is formatted poorly - too many spaces and not easily legible. 

**To Reproduce**
Open roster on mobile - specifically with locked players. 

**Expected behavior**
A cleaner and clearer roster screen for mobile 

**Screenshots**
![6D75984C-962E-46FE-8120-FB26D34CA9EE](https://user-images.githubusercontent.com/92040680/136225915-233919ef-cd85-4af6-9760-dee0494defd6.png)

**Additional context**

**Comment by EnrgyzerBunny** [comment]
Fixed
